### ISSUE TITLE
Load_cell output val: NAN 

### ISSUE THREAD

**Issue by YPayal** [olkal/HX711_ADC#111]
I am getting "Load_cell output val: NAN " my connections are perfectly fine. Can someone help me with this.

**Comment by olkal** [comment]
Hi
NAN is short for "not a number" and means that the value is not a valid printable number. 
Similar reported issues have turned out to be incorrect wiring from the HX711 module to the mcu IO pins, or blown or incompatible IO pins. Please double check that the clk and dout pin/wiring is correct and that the mcu IO pins that you are using are working, and that the HX711 have power. If you have another mcu available, try to replace it.

**Comment by YPayal** [comment]
![WhatsApp Image 2022-10-06 at 15 28 55](https://user-images.githubusercontent.com/95932030/194285194-f319dc0c-fcda-4df0-b287-823d3157b675.jpg)
![WhatsApp Image 2022-10-06 at 15 28 55](https://user-images.githubusercontent.com/95932030/194285253-26fc10c8-bb6a-4b61-8efb-cedb6a4055a4.jpg)
![WhatsApp Image 2022-10-06 at 15 28 56](https://user-images.githubusercontent.com/95932030/194285289-0feb0dc1-0a66-4b50-9a83-caf93bca80be.jpg)
I am uploading the photos of my set up, can you let me know where am I going wrong, It would be a great help

**Comment by olkal** [comment]
Hi
I can't see anything wrong in the pictures. 
I can't see how you conneted the HX711's VCC and GND, but I assume that they go to the Arduino 5V and GND.
Check that pin 4 and 5 are actually working as outputs by using a LED and the Blink.ino example, or try to use some other output pins.

**Comment by YPayal** [comment]
Hey @olkal Thanks for your previous message, the code is working now the issue was with the wiring.

**Comment by YPayal** [comment]
Hey @olkal I am doing a need project with arduino, basically I want to set an constant humidity chamber and I am not really good at coding, was hoping if you could help me.

**Comment by YPayal** [comment]
Hey @olkal I am doing a new project with arduino, basically I want to set an constant humidity chamber with BME280 sensor and I am not really good at coding, was hoping if you could help me.
